### ISSUE TITLE
Enable syslog?

### ISSUE THREAD

**Issue by d4np3** [rnwolfe/fmc-tools#7]
Am I missing something or does this only set the override/server and not actually enable syslog itself if it is not configured?

I have a 300+ ruleset without syslog, and it bails out as follows on TCAT:

"syslogSeverity or syslogConfig cannot be specified without setting enableSyslog to true"

It did work for a couple of rules where I manually enabled the log to syslog checkbox.

**Comment by rnwolfe** [comment]
Been a while since I worked on this and the FMC API could have changed a little, but if I recall correctly, you have to specify whether to log at the end or start of a session to enable syslog. 

Example below. This is in the README file, as well.

```

# Logging settings
#  Leave variable empty (var = '') if you don't want to include the setting
syslog_to_server = 'api-syslog-server'
log_to_fmc = 'true'
log_at_begin = 'false'
log_at_end = 'true'

```

If the API did change a bit for syslog settings, you could update the script pretty easily to include the new field.

**Comment by d4np3** [comment]
Thanks for the reply! Yeah there is a log to syslog option that is the same as the connection check boxes. Then the syslog server is the overriding sub option. Like you have log_to_fmc, I expect you would need a log_to_syslog in addition to the syslog_to_server (which sets the default override instead of master syslog)

**Comment by rnwolfe** [comment]
Yes, sounds like the settings changed a bit since I made this. But it
sounds like you just need to add a syslogEnabled setting to the payload.

Should be an easy change for you to make. I don’t really maintain this and
don’t have an FMC readily available to test with.

**Comment by d4np3** [comment]
Thanks mate. I'll give it a go

**Comment by d4np3** [comment]
I got it working. I changed your old syslog server config to syslog override (which is the alert override setting it does set in the newer versions if checkbox is already enabled)

Here is the gist of the basic enable syslog check box.

      log_to_syslog = 'true'

      if 'enableSyslog' not in acp_rule:
            # Get the existing rule configuration
            # Set syslog configuration
            payload['enableSyslog'] = {
                'id': log_to_syslog
            }
        else:
            print('  Syslog logging already exists, or not specified. Skipping syslog config.')

     if log_to_syslog and ('enableSyslog' not in acp_rule or 'enableSyslog' != log_to_syslog):
            payload['enableSyslog'] = log_to_syslog
        else:
            print('  Log to Syslog not already set, or not specified. Skipping log to syslog.')

            payload['enableSyslog'] = 'true'
