### ISSUE TITLE
Not very secure, try this instead

### ISSUE THREAD

**Issue by Westy-87** [rnwolfe/fmc-tools#8]
I don't have this script automated, and prefer not to leave the username and password written in the code. So I modified it to input at time of running.

```
import getpass
print ("Enter username with API access")
username = input("Username: ")
password = getpass.getpass()
```

**Comment by rnwolfe** [comment]
Yes, you're right. I wrote this a while ago and wasn't very concerned about that for the use case. 

It could pretty easily be adapted to use `getpass` as you did here, or to let it be passed it as a command line argument which has become my standard approach for new things I'm coding nowadays (e.g. https://github.com/ironbow/webex-teams-bulk-add).
